# 市场非流动性

In [1]:
## 导入NumPy、Pandas、Wind
import numpy as np
import pandas as pd
import statsmodels.api as sm
from WindPy import w
import datetime

In [2]:
w.start() # 默认命令超时时间为120秒，如需设置超时时间可以加入waitTime参数，例如waitTime=60,即设置命令超时时间为60秒  
w.isconnected() # 判断WindPy是否已经登录成功

Welcome to use Wind Quant API for Python (WindPy)!

COPYRIGHT (C) 2020 WIND INFORMATION CO., LTD. ALL RIGHTS RESERVED.
IN NO CIRCUMSTANCE SHALL WIND BE RESPONSIBLE FOR ANY DAMAGES OR LOSSES CAUSED BY USING WIND QUANT API FOR Python.

True

## 导入已有的证券数据

In [6]:
## 直接读取样本股票代码
codes = pd.read_csv('Raw Transaction Data/AllCorps.csv', encoding = "utf-8", skiprows= 1, header= None)
codes = codes[0].tolist()
codes.sort()
len(codes)

3567

In [8]:
## 读取权重数据
weight = pd.read_csv('Weight and Ave/weight.csv')

In [9]:
## 导入证券日涨跌幅数据
pctdt = pd.read_csv('Raw Transaction Data/transdt.csv')

In [10]:
## 转为一维表
pctdt_d1  = pd.melt(pctdt, 
            id_vars = 'index', 
            value_vars =list(pctdt.columns[1:]), 
            var_name='code', 
            value_name='pctchg')
pctdt_d1.columns = ['date', 'code', 'pctchg']
pctdt_d1['date'] = pd.to_datetime(pctdt_d1['date'])
pctdt_d1['pctchg'] = abs(pctdt_d1['pctchg'] * 0.01)

In [11]:
pctdt_d1

               date       code    pctchg
0        2007-01-04  000001.SZ  0.024879
1        2007-01-05  000001.SZ  0.074415
2        2007-01-08  000001.SZ  0.023737
3        2007-01-09  000001.SZ  0.032162
4        2007-01-10  000001.SZ  0.020290
...             ...        ...       ...
10412068 2018-12-24  600680.SH       NaN
10412069 2018-12-25  600680.SH       NaN
10412070 2018-12-26  600680.SH       NaN
10412071 2018-12-27  600680.SH       NaN
10412072 2018-12-28  600680.SH       NaN

[10412073 rows x 3 columns]

### 使用Wind下载涨跌幅和交易量数据

In [12]:
vlm_07 = w.wsd(codes, "amt", "2007-01-01", "2007-12-31", "Currency=CNY;PriceAdj=F")
vlm_2007 = pd.DataFrame(vlm_07.Data,index = vlm_07.Codes,columns = vlm_07.Times)
vlm_2007 = vlm_2007.T
vlm_2007 = vlm_2007.reset_index()

In [13]:
vlm_08 = w.wsd(codes, "amt", "2008-01-01", "2008-12-31", "Currency=CNY;PriceAdj=F")
vlm_2008 = pd.DataFrame(vlm_08.Data,index = vlm_08.Codes,columns = vlm_08.Times)
vlm_2008 = vlm_2008.T
vlm_2008 = vlm_2008.reset_index()

In [14]:
vlm_09 = w.wsd(codes, "amt", "2009-01-01", "2009-12-31", "Currency=CNY;PriceAdj=F")
vlm_2009 = pd.DataFrame(vlm_09.Data,index = vlm_09.Codes,columns = vlm_09.Times)
vlm_2009 = vlm_2009.T
vlm_2009 = vlm_2009.reset_index()

In [15]:
vlm_10 = w.wsd(codes, "amt", "2010-01-01", "2010-12-31", "Currency=CNY;PriceAdj=F")
vlm_2010 = pd.DataFrame(vlm_10.Data,index = vlm_10.Codes,columns = vlm_10.Times)
vlm_2010 = vlm_2010.T
vlm_2010 = vlm_2010.reset_index()

In [16]:
vlm_11 = w.wsd(codes, "amt", "2011-01-01", "2011-12-31", "Currency=CNY;PriceAdj=F")
vlm_2011 = pd.DataFrame(vlm_11.Data,index = vlm_11.Codes,columns = vlm_11.Times)
vlm_2011 = vlm_2011.T
vlm_2011 = vlm_2011.reset_index()

In [17]:
vlm_12 = w.wsd(codes, "amt", "2012-01-01", "2012-12-31", "Currency=CNY;PriceAdj=F")
vlm_2012 = pd.DataFrame(vlm_12.Data,index = vlm_12.Codes,columns = vlm_12.Times)
vlm_2012 = vlm_2012.T
vlm_2012 = vlm_2012.reset_index()

In [18]:
vlm_13 = w.wsd(codes, "amt", "2013-01-01", "2013-12-31", "Currency=CNY;PriceAdj=F")
vlm_2013 = pd.DataFrame(vlm_13.Data,index = vlm_13.Codes,columns = vlm_13.Times)
vlm_2013 = vlm_2013.T
vlm_2013 = vlm_2013.reset_index()

In [19]:
vlm_14 = w.wsd(codes, "amt", "2014-01-01", "2014-12-31", "Currency=CNY;PriceAdj=F")
vlm_2014 = pd.DataFrame(vlm_14.Data,index = vlm_14.Codes,columns = vlm_14.Times)
vlm_2014 = vlm_2014.T
vlm_2014 = vlm_2014.reset_index()

In [20]:
vlm_15 = w.wsd(codes, "amt", "2015-01-01", "2015-12-31", "Currency=CNY;PriceAdj=F")
vlm_2015 = pd.DataFrame(vlm_15.Data,index = vlm_15.Codes,columns = vlm_15.Times)
vlm_2015 = vlm_2015.T
vlm_2015 = vlm_2015.reset_index()

In [21]:
vlm_16 = w.wsd(codes, "amt", "2016-01-01", "2016-12-31", "Currency=CNY;PriceAdj=F")
vlm_2016 = pd.DataFrame(vlm_16.Data,index = vlm_16.Codes,columns = vlm_16.Times)
vlm_2016 = vlm_2016.T
vlm_2016 = vlm_2016.reset_index()

In [22]:
vlm_17 = w.wsd(codes, "amt", "2017-01-01", "2017-12-31", "Currency=CNY;PriceAdj=F")
vlm_2017 = pd.DataFrame(vlm_17.Data,index = vlm_17.Codes,columns = vlm_17.Times)
vlm_2017 = vlm_2017.T
vlm_2017 = vlm_2017.reset_index()

In [23]:
vlm_18 = w.wsd(codes, "amt", "2018-01-01", "2018-12-31", "Currency=CNY;PriceAdj=F")
vlm_2018 = pd.DataFrame(vlm_18.Data,index = vlm_18.Codes,columns = vlm_18.Times)
vlm_2018 = vlm_2018.T
vlm_2018 = vlm_2018.reset_index()

In [24]:
## 保存交易量数据
vlm0 = pd.concat([vlm_2007, vlm_2008, vlm_2009, vlm_2010, vlm_2011, vlm_2012, vlm_2013, vlm_2014, vlm_2015, vlm_2016, vlm_2017, vlm_2018], ignore_index=True)
vlm0.to_csv('Raw Transaction Data/vlm', index=False)

In [25]:
vlm0 = pd.read_csv('Raw Transaction Data/vlm')

In [26]:
vlm_d1  = pd.melt(vlm0, 
            id_vars = 'index', 
            value_vars =list(vlm0 .columns[1:]), 
            var_name='code', 
            value_name='volumn')
vlm_d1.columns = ['date', 'code', 'volumn']
vlm_d1['date'] = pd.to_datetime(vlm_d1['date'])
vlm_d1['year'] = vlm_d1['date'].dt.year
vlm_d1['month'] = vlm_d1['date'].dt.month
vlm_d1['volumn'] = vlm_d1['volumn'] / 1000000

In [27]:
## 合并pctchg与vlm数据
ilqdt_dt = pd.merge(pctdt_d1, vlm_d1, on = ['code', 'date'], how = 'left')
ilqdt_dt = ilqdt_dt.dropna(subset = ['pctchg', 'volumn'])
ilqdt_dt = ilqdt_dt[['code', 'date', 'year', 'month', 'pctchg', 'volumn']]
ilqdt_dt = ilqdt_dt[ilqdt_dt['volumn'] != 0]
ilqdt_dt['indct'] = ilqdt_dt['pctchg'] / ilqdt_dt['volumn']

In [28]:
ilqdt_dt

               code       date  year  month    pctchg       volumn     indct
0         000001.SZ 2007-01-04  2007      1  0.024879  1016.722868  0.000024
1         000001.SZ 2007-01-05  2007      1  0.074415   715.011004  0.000104
2         000001.SZ 2007-01-08  2007      1  0.023737   421.819403  0.000056
3         000001.SZ 2007-01-09  2007      1  0.032162   650.410192  0.000049
4         000001.SZ 2007-01-10  2007      1  0.020290   619.003214  0.000033
...             ...        ...   ...    ...       ...          ...       ...
10411902  600680.SH 2018-04-23  2018      4  0.050272    25.794177  0.001949
10411903  600680.SH 2018-04-24  2018      4  0.047865    28.879083  0.001657
10411904  600680.SH 2018-04-25  2018      4  0.001359    16.557966  0.000082
10411905  600680.SH 2018-04-26  2018      4  0.002721    23.484744  0.000116
10411906  600680.SH 2018-04-27  2018      4  0.043419    34.983984  0.001241

[6420636 rows x 7 columns]

In [30]:
## 计算各公司非流动性
illiq_cmp = ilqdt_dt.groupby([ilqdt_dt['code'], ilqdt_dt['year'], ilqdt_dt['month']])['indct'].mean()
illiq_cmp = illiq_cmp.reset_index()

## 等权重加权法

In [31]:
illiq_ew = illiq_cmp.groupby([illiq_cmp['year'], illiq_cmp['month']])['indct'].agg([('illiq', 'mean'),])
illiq_ew = illiq_ew.reset_index()

In [32]:
illiq_ew1 = illiq_ew.head(97).drop(index = 0, axis = 0).reset_index(drop = True)
illiq_ew1["illiq"] = np.log(illiq_ew1["illiq"])
illiq_ew0 = illiq_ew.head(96)
illiq_ew0["illiq"] = np.log(illiq_ew0["illiq"])

D:\Python\programs\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [33]:
illiq_ewx = sm.add_constant(illiq_ew0["illiq"])
model_ew = sm.OLS(illiq_ew1["illiq"], illiq_ewx)
results_ew = model_ew.fit()
print(results_ew.summary())

OLS Regression Results
==============================================================================
Dep. Variable:                  illiq   R-squared:                       0.476
Model:                            OLS   Adj. R-squared:                  0.471
Method:                 Least Squares   F-statistic:                     85.45
Date:                Sun, 11 Apr 2021   Prob (F-statistic):           7.45e-15
Time:                        12:41:16   Log-Likelihood:                -95.391
No. Observations:                  96   AIC:                             194.8
Df Residuals:                      94   BIC:                             199.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -2.0594      0.512     -4.023      0.000      -3.076      -1.043
illiq          0.6944      0.075      9.244      0.000       0.545       0.844
==============================================================================
Omnibus:                       55.720   Durbin-Watson:                   2.050
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              325.539
Skew:                           1.729   Prob(JB):                     2.04e-71
Kurtosis:                      11.332   Cond. No.                         52.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [34]:
ILLIQE_ew = -2.0594 + 0.6944 * illiq_ew['illiq']
ILLIQE_ew.head(96).to_csv("Rgrss/ILLIQE_ew.csv", index = False)

## 市值加权法

In [35]:
## 合并权重数据，加权
illiq = pd.merge(illiq_cmp, weight, on = ['code', 'year', 'month'], how = 'left')
illiq['illiq'] = illiq['indct'] * illiq['weight']

In [36]:
## 计算市场不流动性
illiq_mkt = illiq.groupby([illiq['year'], illiq['month']])['illiq'].agg([('Amihud', 'sum'),])
illiq_mkt = illiq_mkt.reset_index()

In [37]:
illiq_mkt.to_csv("Rgrss/illiq_vw.csv", index = False)

In [39]:
illiq_vw = pd.read_csv("Rgrss/illiq_vw.csv")

In [40]:
illiq_vw1 = illiq_vw.head(97).drop(index = 0, axis = 0).reset_index(drop = True)
illiq_vw1["Amihud"] = np.log(illiq_vw1["Amihud"])
illiq_vw0 = illiq_vw.head(96)
illiq_vw0["Amihud"] = np.log(illiq_vw0["Amihud"])

D:\Python\programs\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [41]:
illiq_vwx = sm.add_constant(illiq_vw0["Amihud"])
model_vw = sm.OLS(illiq_vw1["Amihud"], illiq_vwx)
results_vw = model_vw.fit()
print(results_vw.summary())

OLS Regression Results
==============================================================================
Dep. Variable:                 Amihud   R-squared:                       0.513
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     98.85
Date:                Sun, 11 Apr 2021   Prob (F-statistic):           2.44e-16
Time:                        12:42:47   Log-Likelihood:                -52.960
No. Observations:                  96   AIC:                             109.9
Df Residuals:                      94   BIC:                             115.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -2.3501      0.593     -3.961      0.000      -3.528      -1.172
Amihud         0.7155      0.072      9.942      0.000       0.573       0.858
==============================================================================
Omnibus:                        3.236   Durbin-Watson:                   2.133
Prob(Omnibus):                  0.198   Jarque-Bera (JB):                2.652
Skew:                           0.274   Prob(JB):                        0.265
Kurtosis:                       3.602   Cond. No.                         115.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [42]:
ILLIQE_vw = -2.3501 + 0.7155 * illiq_vw['Amihud']
ILLIQE_vw.head(96).to_csv("Rgrss/ILLIQE_vw.csv", index = False)