# 分板块研究平均偏度、峰度影响：中小板

In [1]:
## 导入NumPy、Pandas、Wind
import numpy as np
import pandas as pd
from scipy import stats
from WindPy import w
import datetime
from dateutil.relativedelta import relativedelta

In [2]:
## 读入个股收益率各月的方差、偏度、峰度
prdct0 = pd.read_csv('Raw Transaction Data/prdct_dt.csv')
## 读入上市公司代码与上市板块
board = pd.read_csv('Raw Transaction Data/AllCorps.csv')
## 合并指标值与板块信息
prdct_mk = pd.merge(prdct0, board, left_on = 'code', right_on = 'codes', how = 'left')

In [3]:
## 启动Wind终端的API
## 判断WindPy是否已经登录成功
w.start() 
w.isconnected()

Welcome to use Wind Quant API for Python (WindPy)!

COPYRIGHT (C) 2020 WIND INFORMATION CO., LTD. ALL RIGHTS RESERVED.
IN NO CIRCUMSTANCE SHALL WIND BE RESPONSIBLE FOR ANY DAMAGES OR LOSSES CAUSED BY USING WIND QUANT API FOR Python.

True

In [4]:
## 读取shibor数据
shibor = w.wsd("SHIBORON.IR", "open", "2007-01-01", "2019-01-31")
shibor = pd.DataFrame(shibor.Data,index = shibor.Codes,columns = shibor.Times)
shibor = shibor.T
shibor = shibor.reset_index()
shibor.columns = ['date', 'shibor']
shibor['shibor'] = shibor['shibor'] * 0.01
shibor['date'] = pd.to_datetime(shibor['date'])
shibor['year'] = shibor['date'].dt.year
shibor['month'] = shibor['date'].dt.month

In [5]:
## 计算各月shibor均值
intrst = shibor.groupby([shibor['year'], shibor['month']])['shibor'].agg([('mn_SHIBOR', 'mean'), ])
intrst = intrst.reset_index()
intrst = intrst.reset_index()
intrst.columns = ['index', 'year', 'month', 'shibor']

In [6]:
## 保留创业板指标
prdct = prdct_mk[prdct_mk['boardtype'] == '创业板']
prdct = prdct.reset_index(drop = True)
prdct = prdct.sort_values(by= ["code", 'year', 'month'] , ascending = True)

In [7]:
codes = prdct['code'].tolist()
codes = list(set(codes))
len(codes)

738

## 计算领先一期的超额收益率

In [8]:
## 指数月收益数据
mkt_r = w.wsd("399102.SZ", "pct_chg", "2007-01-01", "2019-01-31", "Period=M;TradingCalendar=SZSE")
mkt_r = pd.DataFrame(mkt_r.Data, index = mkt_r.Codes, columns = mkt_r.Times)
mkt_r = mkt_r.T
mkt_r = mkt_r.reset_index()
mkt_r.columns = ['date', 'pct_chg']
mkt_r['date'] = pd.to_datetime(mkt_r['date'])
mkt_r['pct_chg'] = mkt_r['pct_chg'] * 0.01
mkt_r = mkt_r.reset_index()

In [9]:
## 计算月超额收益率
mkt_exr = pd.merge(mkt_r, intrst, on = 'index', how = 'left')
mkt_exr['exr'] = mkt_exr['pct_chg'] - mkt_exr['shibor']
mkt_exr = mkt_exr[['index', 'exr', 'year', 'month', 'date']]

In [10]:
mkt_r0 = mkt_exr.head(144)
mkt_r0.columns = ['index', 'r0', 'year', 'month', 'date']

In [11]:
## 删除首行，得到领先一期的收益率
mkt_exr = mkt_exr[['exr', 'year', 'month']]
mkt_exr = mkt_exr.drop(0, axis = 0)
mkt_exr = mkt_exr.reset_index(drop = True)
mkt_exr = mkt_exr.reset_index()

## 计算市场方差、偏度、峰度

In [12]:
## 获得创业板综指的指数数据
trdt_mk = w.wsd("399102.SZ", "swing", "2007-01-01", "2019-01-31", "TradingCalendar=SZSE")
trdt_mk = pd.DataFrame(trdt_mk.Data, index = trdt_mk.Codes, columns = trdt_mk.Times)
trdt_mk = trdt_mk.T
trdt_mk = trdt_mk.reset_index()
trdt_mk.columns = ['date', 'pct_chg']
trdt_mk['pct_chg'] = trdt_mk['pct_chg'] * 0.01
trdt_mk['date'] = pd.to_datetime(trdt_mk['date'])
trdt_mk['year'] = trdt_mk['date'].dt.year
trdt_mk['month'] = trdt_mk['date'].dt.month

In [13]:
## 合并中小板综指数据和shibor收益数据
mkt_dt = pd.merge(trdt_mk, shibor[['date', 'shibor']], on = 'date', how = 'left')
mkt_dt['exr'] = mkt_dt['pct_chg'] - mkt_dt['shibor']
mkt_dt = mkt_dt[['year', 'month', 'date', 'pct_chg', 'shibor', 'exr']]

In [14]:
## 分组，计算各月均值、方差、偏度、峰度
mkt_sta = mkt_dt.groupby([mkt_dt['year'], mkt_dt['month']])['exr'].agg([('num', 'count'), ('mean', 'mean'), ('math_var', 'var'), ('math_skew', 'skew'),('math_kurt', stats.kurtosis),])
mkt_sta = mkt_sta.reset_index()

In [15]:
## 删除首行
mkt_lf = mkt_dt.groupby([mkt_dt['year'], mkt_dt['month']])['date'].first()
mkt_lf = mkt_lf.reset_index()
mkt_lf.insert(2, 'flag', np.ones(len(mkt_lf)))
mkt_lf = mkt_lf[['date', 'flag']]

## 保留其他数据
mkt_wof = pd.merge(mkt_dt, mkt_lf, on = 'date', how = 'left')
mkt_wof = mkt_wof[mkt_wof['flag'] != 1]
mkt_wof = mkt_wof[['date', 'exr']]
mkt_wof = mkt_wof.rename(columns={'exr': 'exr_f'})
mkt_wof.insert(2, 'order', np.arange(len(mkt_wof)))

## 删除末行
mkt_ll = mkt_dt.groupby([mkt_dt['year'], mkt_dt['month']])['date'].last()
mkt_ll = mkt_ll.reset_index()
mkt_ll.insert(2, 'flag', np.ones(len(mkt_ll)))
mkt_ll = mkt_ll[['date', 'flag']]

## 保留其他数据
mkt_wol = pd.merge(mkt_dt, mkt_ll, on = 'date', how = 'left')
mkt_wol = mkt_wol[mkt_wol['flag'] != 1]
mkt_wol = mkt_wol[['year', 'month', 'exr']]
mkt_wol = mkt_wol.rename(columns={'exr': 'exr_l'})
mkt_wol.insert(2, 'order', np.arange(len(mkt_wol)))

## 合并去除第一行/最后一行的数据，准备计算调整的方差
## 注意，保留的日期系exr_f的日期
mkt_ajsta0 = pd.merge(mkt_wol, mkt_wof, on = 'order', how = 'left')
mkt_ajsta0 = mkt_ajsta0[[ 'year', 'month', 'date', 'exr_f', 'exr_l']]

## 合并均值数据
mkt_ajsta = pd.merge(mkt_ajsta0, mkt_sta[['year', 'month', 'mean']], on = ['year', 'month'], how = 'left')
mkt_ajsta['diff1'] = mkt_ajsta['exr_f'] - mkt_ajsta['mean']
mkt_ajsta['diff2'] = mkt_ajsta['exr_l'] - mkt_ajsta['mean']
mkt_ajsta['product'] = mkt_ajsta['diff1'] * mkt_ajsta['diff2']
mkt_ajsta = mkt_ajsta.groupby([mkt_ajsta['year'], mkt_ajsta['month']])['product'].agg([('prdct', 'sum'),])
mkt_ajsta = mkt_ajsta.reset_index()

## 合并调整后的数据和原统计指标值
mkt_ajs = pd.merge(mkt_sta, mkt_ajsta, on = ['year', 'month'], how = 'left' )
mkt_ajs['var'] = mkt_ajs['math_var'] * mkt_ajs['num'] + 2* mkt_ajs['prdct']
mkt_ajs['adj_var'] = mkt_ajs['var']/mkt_ajs['num']

## 保留数据
mkt_prdct = mkt_ajs[['year', 'month', 'num', 'mean', 'var', 'adj_var', 'math_skew', 'math_kurt']]
mkt_prdct = mkt_prdct[['year', 'month', 'var', 'math_skew', 'math_kurt']]
mkt_prdct.columns = ['year', 'month', 'mkt_var', 'mkt_skew', 'mkt_kurt']

In [16]:
mkt_prdct

     year  month   mkt_var  mkt_skew  mkt_kurt
0    2007      1       NaN       NaN       NaN
1    2007      2       NaN       NaN       NaN
2    2007      3       NaN       NaN       NaN
3    2007      4       NaN       NaN       NaN
4    2007      5       NaN       NaN       NaN
..    ...    ...       ...       ...       ...
140  2018      9  0.000406 -0.377135 -1.260054
141  2018     10  0.002534  0.606260 -0.996331
142  2018     11  0.001338  1.084392  0.128041
143  2018     12  0.001712  0.952776  0.136288
144  2019      1  0.002488  1.563470  2.579388

[145 rows x 5 columns]

## 等权重加权法

In [17]:
## 计算创业板平均方差、偏度与峰度
mnv_ew = prdct.groupby([prdct['year'], prdct['month']])['var', 'adj_var', 'math_skew', 'math_kurt'].mean()
mnv_ew = mnv_ew.reset_index()
mnv_ew = mnv_ew[['year', 'month', 'adj_var', 'math_skew', 'math_kurt']]
mnv_ew.columns = ['year', 'month', 'var_ew', 'skew_ew', 'kurt_ew']

In [18]:
mnv_ew

     year  month    var_ew   skew_ew   kurt_ew
0    2009     11  0.002639 -0.510508 -0.108868
1    2009     12  0.001457 -0.191957  0.156872
2    2010      1  0.001897  0.791106  1.668415
3    2010      2  0.001022  0.013159  0.437106
4    2010      3  0.000723 -0.059888  0.096379
..    ...    ...       ...       ...       ...
105  2018      8  0.000861  0.271952  0.239175
106  2018      9  0.000535 -0.039269  0.448894
107  2018     10  0.001494 -0.507425  0.645489
108  2018     11  0.000980 -0.124778  0.820701
109  2018     12  0.000688  0.144679  0.271331

[110 rows x 5 columns]

## 市值加权法

In [19]:
## 读取市值数据
evdt = w.wsd(codes, "ev", "2006-12-01", "2018-11-30", "unit=1;Period=M;TradingCalendar=SZSE")
ev = pd.DataFrame(evdt.Data, index = evdt.Codes, columns = evdt.Times)
ev = ev.T
ev = ev.reset_index()

In [20]:
## 转为一维表，准备合并
ev_T = pd.melt(ev, 
            id_vars = 'index', 
            value_vars = list(ev.columns[1:]), 
            var_name='code', 
            value_name='ev_month')
ev_T.columns = ['date', 'code', 'ev_month']
ev_T['date'] = pd.to_datetime(ev_T['date'])
ev_T['date'] = ev_T['date'].apply(lambda x: x + relativedelta(months = +1)) 
## 生成年、月
ev_T['year'] = ev_T['date'].dt.year
ev_T['month'] = ev_T['date'].dt.month

In [21]:
## 合并prdct和ev_w
vw_fore = pd.merge(prdct, ev_T, on = ['code', 'year', 'month'], how = 'left')
vw_fore = vw_fore.dropna().reset_index(drop = True)

## 按月分组，计算各月总市值
## 计算样本数据的权重
tt_ev = vw_fore.groupby([vw_fore['year'], vw_fore['month']])['ev_month'].agg([('TEV', 'sum'),])
tt_ev = tt_ev.reset_index()
ev_w = pd.merge(vw_fore, tt_ev, on = ['year', 'month'], how = 'left')
ev_w['weight'] = ev_w['ev_month']/ ev_w['TEV']
ev_w = ev_w.sort_values(by= ["code", 'year', 'month'] , ascending = True)

In [22]:
ev_w

,code,year,month,num,var,adj_var,math_skew,math_kurt,codes,boardtype,date,ev_month,TEV,weight
0,300001.SZ,2009,11,21,0.052577,0.002504,-0.731528,-0.141233,300001.SZ,创业板,2009-11-30,5.878400e+09,1.399674e+11,0.041998
1,300001.SZ,2009,12,23,0.020632,0.000897,-0.396938,-0.372213,300001.SZ,创业板,2009-12-30,6.268512e+09,1.445010e+11,0.043380
2,300001.SZ,2010,1,20,0.014681,0.000734,0.299213,0.625364,300001.SZ,创业板,2010-01-31,5.643264e+09,1.610084e+11,0.035050
3,300001.SZ,2010,2,15,0.025158,0.001677,-0.833630,0.187893,300001.SZ,创业板,2010-02-28,4.864376e+09,1.843256e+11,0.026390
4,300001.SZ,2010,3,23,0.026632,0.001158,0.608117,0.721363,300001.SZ,创业板,2010-03-26,5.263840e+09,2.324507e+11,0.022645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44549,300750.SZ,2018,12,20,0.004244,0.000212,0.139163,-0.120247,300750.SZ,创业板,2018-12-30,1.756672e+11,4.239045e+12,0.041440
44550,300751.SZ,2018,12,20,0.015891,0.000795,-0.599014,-0.276630,300751.SZ,创业板,2018-12-30,6.644560e+09,4.239045e+12,0.001567
44551,300752.SZ,2018,12,20,0.161407,0.008070,0.066487,-1.607825,300752.SZ,创业板,2018-12-30,2.183469e+09,4.239045e+12,0.000515
44552,300760.SZ,2018,11,22,0.003906,0.000178,1.308318,2.043055,300760.SZ,创业板,2018-11-30,1.203534e+11,4.016866e+12,0.029962
44553,300760.SZ,2018,12,20,0.022132,0.001107,-0.696486,0.213454,300760.SZ,创业板,2018-12-30,1.367653e+11,4.239045e+12,0.032263

In [23]:
## 筛选需要的指标列
vw = ev_w[['code', 'year', 'month', 'weight', 'var', 'adj_var', 'math_skew', 'math_kurt']]

## 计算加权指标
vw['var_vw'] = vw['adj_var'] * vw['weight']
vw['skew_vw'] = vw['math_skew'] * vw['weight']
vw['kurt_vw'] = vw['math_kurt'] * vw['weight']

## 按月加总
mnv_vw = vw.groupby([vw['year'], vw['month']])['var_vw', 'skew_vw', 'kurt_vw'].sum()
mnv_vw = mnv_vw.reset_index()
mnv_vw = mnv_vw[['year', 'month', 'var_vw', 'skew_vw', 'kurt_vw']]

## 合并数据

In [24]:
mkt_reg = pd.merge(mkt_exr[['index', 'exr']], mkt_r0, on = 'index', how = 'left')
mkt_reg = pd.merge(mkt_reg, mkt_prdct, on = ['year', 'month'], how = 'left')
mkt_reg = pd.merge(mkt_reg, mnv_ew, on = ['year', 'month'], how = 'left')
mkt_reg = pd.merge(mkt_reg, mnv_vw, on = ['year', 'month'], how = 'left')
mkt_reg = mkt_reg.drop(['index', 'year', 'month'], axis = 1)
mkt_reg = mkt_reg.dropna()
mkt_reg.columns = ['r', 'r0', 'date','mkt_var', 'mkt_skew', 'mkt_kurt', 'var_ew', 'skew_ew', 'kurt_ew', 'var_vw', 'skew_vw', 'kurt_vw']
mkt_reg = mkt_reg.reset_index(drop = True)

In [25]:
mkt_reg[mkt_reg['date'] < '2015-01-01'].to_csv("Plot/reg_mkt3.csv", index = False)

In [26]:
mkt_reg[mkt_reg['date'] < '2015-01-01']

,r,r0,date,mkt_var,mkt_skew,mkt_kurt,var_ew,skew_ew,kurt_ew,var_vw,skew_vw,kurt_vw
0,0.036843,-0.102268,2010-06-30,0.005363,0.548418,-0.471148,0.002085,-0.298269,-0.310924,0.002204,-0.288895,-0.243211
1,0.042345,0.036843,2010-07-30,0.003642,0.710287,-0.458944,0.000829,-0.185315,0.323053,0.000849,-0.167537,0.095654
2,-0.100472,0.042345,2010-08-31,0.000766,0.431462,0.616646,0.002605,0.107612,0.782267,0.000546,-0.070916,0.156086
3,0.113241,-0.100472,2010-09-30,0.001503,0.763375,0.028566,0.001933,0.103414,0.249038,0.000758,-0.031506,-0.182028
4,0.081943,0.113241,2010-10-29,0.005150,2.901298,6.556917,0.001117,0.642776,0.417207,0.000925,0.562810,0.318343
5,-0.065886,0.081943,2010-11-30,0.007173,0.567322,-0.857830,0.002072,0.087882,0.142714,0.001128,-0.077565,-0.290992
6,-0.139407,-0.065886,2010-12-31,0.008646,-0.087684,-0.225593,0.001750,0.027841,0.250553,0.001379,-0.143416,0.235527
7,0.039703,-0.139407,2011-01-31,0.027992,-0.541770,-0.803451,0.001689,-0.216549,-0.118820,0.001540,-0.289460,-0.193060
8,-0.094045,0.039703,2011-02-28,0.002427,0.060195,-0.678176,0.000741,0.073371,0.026075,0.000405,-0.003552,-0.135723
9,-0.114261,-0.094045,2011-03-31,0.001197,0.927711,-0.085306,0.000585,-0.152789,0.825409,0.000510,-0.183427,0.637449
10,-0.101578,-0.114261,2011-04-29,0.002563,0.261571,1.643765,0.000744,-0.475017,0.286425,0.000722,-0.429281,0.148331
11,-0.038122,-0.101578,2011-05-31,0.002766,-0.009005,-0.612688,0.000985,-0.643477,0.378453,0.000957,-0.636342,0.284675
12,0.033324,-0.038122,2011-06-30,0.012148,-0.631978,-0.338288,0.000826,0.118300,0.394680,0.000769,0.028570,0.253289
13,-0.014710,0.033324,2011-07-29,0.003235,-0.162820,-0.695410,0.002649,0.071940,0.524906,0.000900,-0.007121,0.198983
14,-0.178857,-0.014710,2011-08-31,0.008178,1.434995,0.823797,0.001630,0.064505,0.461811,0.001041,0.049855,0.269886
15,0.036032,-0.178857,2011-09-30,0.000790,-0.393136,-0.534021,0.000879,0.135310,-0.117600,0.000574,0.093445,-0.252028
16,-0.050124,0.036032,2011-10-31,0.005568,0.303190,-0.729469,0.000958,-0.015314,-0.149767,0.000891,-0.052254,-0.265054
17,-0.158909,-0.050124,2011-11-30,0.004845,1.368171,1.067183,0.001216,0.093960,0.418426,0.000781,0.118951,0.194277
18,-0.153859,-0.158909,2011-12-30,0.002682,0.536097,-0.567825,0.001010,-0.080404,-0.121310,0.000984,-0.070732,-0.076060
19,0.108452,-0.153859,2012-01-31,0.003598,0.047105,-0.960622,0.002964,-0.635253,-0.507012,0.003001,-0.666009,-0.468654
20,-0.107202,0.108452,2012-02-29,0.005366,-0.266097,-0.302095,0.000922,0.352028,-0.006034,0.000570,0.244391,-0.231918
21,-0.016080,-0.107202,2012-03-30,0.004252,2.054850,3.862477,0.001805,-0.314290,0.380592,0.001067,-0.352328,0.194149
22,0.041183,-0.016080,2012-04-27,0.003198,1.068590,-0.125636,0.000840,-0.698767,1.375047,0.000776,-0.524489,1.104130
23,-0.029197,0.041183,2012-05-31,0.001824,0.151398,-0.456061,0.000611,0.223897,0.508140,0.000504,0.174422,0.293179
24,-0.119069,-0.029197,2012-06-29,0.001615,0.586550,0.247365,0.000918,0.089665,0.143211,0.000775,0.132165,0.050030
25,0.035543,-0.119069,2012-07-31,0.002401,0.963000,0.766464,0.000985,-0.365922,0.745962,0.000817,-0.333332,0.680432
26,-0.055115,0.035543,2012-08-31,0.003440,1.299939,1.925764,0.000748,0.018455,0.134688,0.000720,-0.032541,0.119651
27,-0.030237,-0.055115,2012-09-28,0.003019,-0.321477,-0.773090,0.001561,-0.198690,-0.222366,0.001424,-0.188415,-0.181034
28,-0.147257,-0.030237,2012-10-31,0.002414,-0.949603,-0.042287,0.000688,-0.080293,0.182359,0.000662,-0.083847,0.148915
29,0.161263,-0.147257,2012-11-30,0.001230,1.761564,3.784119,0.000642,-0.366602,0.418208,0.000575,-0.393226,0.417334
30,0.056316,0.161263,2012-12-31,0.003120,0.337583,1.196776,0.000657,0.006081,0.156823,0.000610,-0.041676,0.264316
31,0.061660,0.056316,2013-01-31,0.000765,1.146192,0.408730,0.000913,0.239917,0.109796,0.000882,0.237676,0.101128
32,-0.034534,0.061660,2013-02-28,0.003355,0.836846,-0.033675,0.000601,0.228026,-0.082896,0.000630,0.191020,-0.165065
33,-0.012288,-0.034534,2013-03-29,0.000816,1.384844,2.206352,0.000759,-0.150073,0.042704,0.000781,-0.112058,-0.044635
34,0.174678,-0.012288,2013-04-26,0.001391,1.505121,1.269365,0.000795,-0.376353,0.025481,0.000887,-0.361243,0.015671
35,-0.141806,0.174678,2013-05-31,0.002786,-0.900530,0.842551,0.001026,0.072017,0.050713,0.001126,0.152675,0.076693
36,0.086246,-0.141806,2013-06-28,0.027970,-0.362923,0.733512,0.002623,-0.644068,0.568345,0.002784,-0.635390,0.655469
37,0.013336,0.086246,2013-07-31,0.001036,0.651840,-0.783661,0.001547,-0.109084,0.290768,0.001610,0.036742,0.369952
38,0.097859,0.013336,2013-08-30,0.002884,0.441788,-0.966704,0.000987,0.205601,0.171020,0.000932,0.279090,0.211950
39,-0.110452,0.097859,2013-09-30,0.000908,0.546103,-0.589529,0.000876,0.123523,0.299739,0.001020,0.123048,0.135671
40,0.095973,-0.110452,2013-10-31,0.001796,0.652757,0.107308,0.001616,0.035327,-0.228413,0.001752,0.071864,-0.351080
41,-0.073803,0.095973,2013-11-29,0.002243,0.341212,-0.854609,0.000916,0.352704,0.374242,0.000882,0.243784,0.189311
42,0.099759,-0.073803,2013-12-31,0.003725,1.697470,1.951904,0.001453,-0.643195,1.638244,0.001408,-0.645394,1.470751
43,-0.043521,0.099759,2014-01-30,0.004244,-0.357613,-0.793143,0.001218,0.087785,-0.111627,0.001142,0.190906,-0.075628
44,-0.093983,-0.043521,2014-02-28,0.014048,1.458684,1.242604,0.001158,-0.186423,-0.304291,0.001166,-0.081566,-0.344906
45,-0.041464,-0.093983,2014-03-31,0.001272,-0.232440,-1.245484,0.001427,-0.121202,0.120415,0.001458,-0.028467,0.219820
46,0.021295,-0.041464,2014-04-30,0.002118,1.563682,2.894637,0.000719,-0.214172,0.537517,0.000682,-0.160910,0.374611
47,0.055417,0.021295,2014-05-30,0.000523,-0.294608,-0.038334,0.000626,0.097770,0.106055,0.000654,0.074437,0.024589
48,-0.051110,0.055417,2014-06-30,0.001184,1.584175,2.687485,0.000776,0.143243,0.660154,0.000727,0.207712,0.699990
49,0.039018,-0.051110,2014-07-31,0.000983,0.803485,0.174621,0.000760,0.085234,0.800875,0.000765,0.003431,0.848184
50,0.085257,0.039018,2014-08-29,0.000189,0.625178,0.188930,0.000707,0.312291,0.866247,0.000512,0.336677,0.810715
51,-0.025830,0.085257,2014-09-30,0.000757,2.877564,7.723836,0.000855,0.275785,1.497217,0.000576,0.233289,1.450185
52,0.022642,-0.025830,2014-10-31,0.000414,1.175572,1.813853,0.000880,0.357663,0.147457,0.000685,0.341084,0.135266
53,-0.128283,0.022642,2014-11-28,0.001355,1.938684,3.155439,0.000841,-0.039951,0.618547,0.000733,0.052921,0.599787
54,0.091345,-0.128283,2014-12-31,0.006168,0.613712,-0.387919,0.002000,-0.220550,0.260299,0.001952,-0.128758,0.219985